const path = require('path');
const fs = require('fs');
const chromium = require('@sparticuz/chromium');
const { chromium: pw } = require('playwright-core');
const OUT = '/tmp/qa_v2'; fs.mkdirSync(OUT, { recursive: true });
(async () => {
  const browser = await pw.launch({ args: chromium.args, executablePath: await chromium.executablePath(), headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message.slice(0, 180)));
  page.on('console', m => { if (m.type() === 'error') errors.push('CONSOLE: ' + m.text().slice(0, 180)); });
  await page.goto('file:///home/user/Goop/vikaas-hq/portfolio/v2/loader.html', { waitUntil: 'load', timeout: 60000 });
  await page.evaluate(async () => { if (document.fonts && document.fonts.ready) await document.fonts.ready; });
  await page.waitForTimeout(900);
  await page.screenshot({ path: path.join(OUT, 'l1-typing.png') });
  const m1 = await page.evaluate(() => ({ word: (document.querySelector('#word')||{}).textContent || null, pct: (document.querySelector('#pct')||{}).textContent || null, enter: !!document.querySelector('#enter') }));
  await page.waitForTimeout(3200);
  await page.screenshot({ path: path.join(OUT, 'l2-mid.png') });
  const m2 = await page.evaluate(() => ({ pct: (document.querySelector('#pct')||{}).textContent || null, term: (document.querySelector('#term')||{}).textContent.slice(0, 60), enter: (document.querySelector('#enter')||{}).classList ? document.querySelector('#enter').classList.contains('show') : null }));
  await page.waitForTimeout(3200);
  await page.screenshot({ path: path.join(OUT, 'l3-done.png') });
  const m3 = await page.evaluate(() => ({ word: (document.querySelector('#word')||{}).textContent || null, pct: (document.querySelector('#pct')||{}).textContent || null, dev: (document.querySelector('#dev')||{}).classList ? getComputedStyle(document.querySelector('#dev')).opacity : null, enterShow: (document.querySelector('#enter')||{}).classList ? document.querySelector('#enter').classList.contains('show') : null, termLast: ((document.querySelector('#term')||{}).textContent || '').split('\n').pop() }));
  await page.click('#enter');
  await page.waitForTimeout(1300);
  const m4 = await page.evaluate(() => ({ leaving: (document.querySelector('#loader')||{}).classList ? document.querySelector('#loader').classList.contains('leaving') : null, href: location.href }));
  console.log('M1', JSON.stringify(m1));
  console.log('M2', JSON.stringify(m2));
  console.log('M3', JSON.stringify(m3));
  console.log('M4', JSON.stringify(m4));
  console.log('ERRORS:', errors.length ? '\n' + errors.join('\n') : 'none');
  await browser.close();
})().catch(e => { console.error('FAIL', e.message); process.exit(1); });
